# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0003_fond_index_period_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='fonds',
            field=models.ManyToManyField(to='sharesWebApp.Fond'),
        ),
    ]
