# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0004_share_fonds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.ForeignKey(db_column='idCurrency', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Currency'),
        ),
        migrations.AlterField(
            model_name='share',
            name='index',
            field=models.ForeignKey(db_column='idIndex', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Index'),
        ),
    ]
