# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0005_auto_20170214_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareFonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('maxPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fond', models.ForeignKey(db_column='idFond', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Fond')),
                ('period', models.ForeignKey(db_column='idPeriod', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Period')),
            ],
        ),
        migrations.AlterField(
            model_name='share',
            name='fonds',
            field=models.ManyToManyField(through='sharesWebApp.ShareFonds', to='sharesWebApp.Fond'),
        ),
        migrations.AddField(
            model_name='sharefonds',
            name='share',
            field=models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Share'),
        ),
    ]
