# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0006_auto_20170214_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharefonds',
            options={'ordering': ['fond', 'share', 'period']},
        ),
        migrations.AlterModelTable(
            name='sharefonds',
            table='ShareFonds',
        ),
    ]
