# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0007_auto_20170214_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharefonds',
            name='fond',
        ),
        migrations.RemoveField(
            model_name='sharefonds',
            name='period',
        ),
        migrations.RemoveField(
            model_name='sharefonds',
            name='share',
        ),
        migrations.RemoveField(
            model_name='share',
            name='fonds',
        ),
        migrations.DeleteModel(
            name='ShareFonds',
        ),
    ]
