# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'Currency',
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
            },
        ),
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iberian', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'Fond',
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'Index',
                'verbose_name': 'Indice',
                'verbose_name_plural': 'Indices',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
            ],
            options={
                'ordering': ['fromDate'],
                'db_table': 'Period',
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ISIN', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20)),
                ('favourite', models.BooleanField()),
                ('description', models.CharField(max_length=8000)),
                ('currency', models.ForeignKey(db_column='idCurrency', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Currency')),
                ('index', models.ForeignKey(db_column='idIndex', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Index')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'Share',
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
            },
        ),
    ]
