# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareFonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('maxPrice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fond', models.ForeignKey(db_column='idFond', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Fond')),
                ('period', models.ForeignKey(db_column='idPeriod', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Period')),
                ('share', models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Share')),
            ],
            options={
                'db_table': 'ShareFonds',
            },
        ),
    ]
