# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0002_sharefonds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharefonds',
            options={'ordering': ['fond', 'share', 'period']},
        ),
        migrations.AddField(
            model_name='share',
            name='fonds',
            field=models.ManyToManyField(through='sharesWebApp.ShareFonds', to='sharesWebApp.Fond'),
        ),
        migrations.AlterModelTable(
            name='sharefonds',
            table='ShareFond',
        ),
    ]
