# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0005_auto_20170215_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=10, verbose_name='S\xedmbolo'),
        ),
    ]
