# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0006_auto_20170215_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['name'], 'verbose_name': 'Mercado', 'verbose_name_plural': 'Mercados'},
        ),
        migrations.AlterField(
            model_name='alarm',
            name='changePriceHigh',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Var. Superior (%)'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='changePriceLow',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Var. Inferior (%)'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='maxPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='L\xedmite Superior'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='minPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='L\xedmite Inferior'),
        ),
        migrations.AlterField(
            model_name='fond',
            name='iberian',
            field=models.BooleanField(verbose_name='Ib\xe9rico'),
        ),
        migrations.AlterField(
            model_name='fond',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='period',
            name='fromDate',
            field=models.DateField(verbose_name='Desde'),
        ),
        migrations.AlterField(
            model_name='period',
            name='toDate',
            field=models.DateField(verbose_name='Hasta'),
        ),
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.ForeignKey(db_column='idCurrency', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Currency', verbose_name='Divisa'),
        ),
        migrations.AlterField(
            model_name='share',
            name='description',
            field=models.CharField(blank=True, max_length=8000, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='share',
            name='favourite',
            field=models.BooleanField(verbose_name='Favorito'),
        ),
        migrations.AlterField(
            model_name='share',
            name='index',
            field=models.ForeignKey(blank=True, db_column='idIndex', null=True, on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Index', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ticker'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='maxPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='minPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio M\xednimo'),
        ),
    ]
