# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0007_auto_20170215_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['share'], 'verbose_name': 'Alarma', 'verbose_name_plural': 'Alarmas'},
        ),
        migrations.AlterModelOptions(
            name='sharefonds',
            options={'ordering': ['fond', 'share', 'period'], 'verbose_name': 'Acciones del Fondo', 'verbose_name_plural': 'Acciones de los Fondos'},
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='fond',
            field=models.ForeignKey(db_column='idFond', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Fond', verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='period',
            field=models.ForeignKey(db_column='idPeriod', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Period', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='share',
            field=models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Share', verbose_name='Acci\xf3n'),
        ),
    ]
