# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0010_auto_20170218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual.'),
        ),
        migrations.AlterField(
            model_name='share',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual.'),
        ),
    ]
