# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0011_auto_20170218_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBuy', models.DateField(verbose_name='Fecha Compra')),
                ('dateSell', models.DateField(verbose_name='Fecha Venta')),
                ('sharesBuy', models.IntegerField(verbose_name='Cantidad Compra')),
                ('sharesSell', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Venta')),
                ('priceBuyUnity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio Unit. Compra')),
                ('priceSellUnity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Unit. Venta')),
                ('comissionBuy', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Comision Compra')),
                ('comissionSell', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Comision Venta')),
                ('broker', models.ForeignKey(db_column='idBroker', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Broker', verbose_name='Broker')),
                ('share', models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Share', verbose_name='Accion')),
            ],
            options={
                'ordering': ['dateBuy'],
                'db_table': 'Transaction',
                'verbose_name': 'Transacci\xf3n',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
