# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0013_auto_20170219_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dateSell',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Venta'),
        ),
    ]
