# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0015_auto_20170219_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('importGross', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Bruto')),
                ('importNet', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Neto')),
                ('currencyValue', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Divisa')),
                ('transaction', models.ForeignKey(db_column='idTransaction', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Transaction', verbose_name='Transacci\xf3n')),
            ],
            options={
                'ordering': ['transaction', 'date'],
                'db_table': 'Dividend',
                'verbose_name': 'Dividendos',
                'verbose_name_plural': 'Dividendos',
            },
        ),
    ]
