# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0016_dividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='update',
            field=models.BooleanField(default=True, verbose_name='Actualizar'),
        ),
    ]
