# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0017_auto_20170219_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'ordering': ['date', 'transaction'], 'verbose_name': 'Dividendos', 'verbose_name_plural': 'Dividendos'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='update',
            field=models.BooleanField(default=True, verbose_name='Actualizar'),
        ),
    ]
