# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0018_auto_20170219_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='currency',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cierre'),
        ),
        migrations.AddField(
            model_name='currency',
            name='openValue',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Apertura'),
        ),
        migrations.AddField(
            model_name='share',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='share',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cierre'),
        ),
        migrations.AddField(
            model_name='share',
            name='openValue',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Apertura'),
        ),
    ]
