# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0020_auto_20170228_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['date'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumen'},
        ),
        migrations.AddField(
            model_name='summary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='dividendGross',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Unit. Venta'),
        ),
        migrations.AddField(
            model_name='summary',
            name='priceBuyTotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Precio Unit. Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='priceSellTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Unit. Venta'),
        ),
    ]
