# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0021_auto_20170228_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='dividendGross',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Dividendos'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceBuyTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total compra'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceSellTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Venta'),
        ),
    ]
