# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0022_auto_20170228_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='dividendGross',
            new_name='dividendGrossCurrent',
        ),
        migrations.AddField(
            model_name='summary',
            name='dividendGrossTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Dividendos'),
        ),
        migrations.AddField(
            model_name='summary',
            name='priceBuyCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Beneficio Bruto'),
        ),
        migrations.AddField(
            model_name='summary',
            name='priceSellCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Beneficio Bruto'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceBuyTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Compra'),
        ),
    ]
