# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0023_auto_20170228_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='profitCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Beneficio Actual'),
        ),
        migrations.AddField(
            model_name='summary',
            name='profitTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Beneficio Total'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceBuyCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Compra'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceSellCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Venta'),
        ),
    ]
