# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0024_auto_20170305_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('importGross', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Bruto')),
                ('currencyValue', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Divisa')),
                ('transaction', models.ForeignKey(db_column='idTransaction', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Transaction', verbose_name='Transacci\xf3n')),
            ],
            options={
                'ordering': ['date', 'transaction'],
                'db_table': 'Right',
                'verbose_name': 'Derechos',
                'verbose_name_plural': 'Derechos',
            },
        ),
    ]
