# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0025_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cierre')),
                ('change', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Cambio (%)')),
                ('openValue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Apertura')),
                ('share', models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Share', verbose_name='Acci\xf3n')),
            ],
            options={
                'db_table': 'ShareHistory',
                'verbose_name': 'Hist\xf3rico Acciones',
                'verbose_name_plural': 'Hist\xf3rico Acciones',
            },
        ),
        migrations.AddField(
            model_name='summary',
            name='liquidationValue',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Valor liquidativo'),
        ),
        migrations.AddField(
            model_name='summary',
            name='numberUnits',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Participaciones'),
        ),
        migrations.AddField(
            model_name='summary',
            name='rightsCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cartera Dividendos'),
        ),
        migrations.AddField(
            model_name='summary',
            name='rightsTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cartera Dividendos'),
        ),
        migrations.AlterField(
            model_name='right',
            name='importGross',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='dividendGrossCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cartera Dividendos'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='dividendGrossTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Dividendos'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceBuyCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cartera Compra'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='priceSellCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cartera Venta'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='profitCurrent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cartera Beneficio'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='profitTotal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Beneficio'),
        ),
    ]
