# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0026_auto_20170308_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharehistory',
            old_name='openValue',
            new_name='open',
        ),
        migrations.RemoveField(
            model_name='share',
            name='ticker',
        ),
        migrations.AddField(
            model_name='share',
            name='tickerGoogle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TickerGoo'),
        ),
        migrations.AddField(
            model_name='share',
            name='tickerYahoo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TickerYah'),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Maximo'),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Minimo'),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volumen'),
        ),
    ]
