# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0028_auto_20170310_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cambio'),
        ),
        migrations.AlterField(
            model_name='share',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cambio (%)'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cambio (%)'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Maximo'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Minimo'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen'),
        ),
    ]
