# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0029_auto_20170310_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharehistory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximo'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Minimo'),
        ),
    ]
