# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0030_auto_20170310_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Importe')),
                ('description', models.CharField(blank=True, max_length=8000, null=True, verbose_name='Notas')),
                ('broker', models.ForeignKey(db_column='idBroker', default=1, on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Broker', verbose_name='Broker')),
            ],
            options={
                'ordering': ['date'],
                'db_table': 'DepositWithdraw',
                'verbose_name': 'DepositosReembolsos',
                'verbose_name_plural': 'DepositosReembolsos',
            },
        ),
        migrations.AlterField(
            model_name='share',
            name='description',
            field=models.CharField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
    ]
