# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0032_auto_20170312_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharehistory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='M\xednimo'),
        ),
    ]
