# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0034_auto_20170312_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['name'], 'verbose_name': 'Acci\xf3n', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-date'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumen'},
        ),
        migrations.RemoveField(
            model_name='summary',
            name='liquidationValue',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='numberUnits',
        ),
        migrations.AddField(
            model_name='summary',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='summary',
            name='R',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RentabilidadHoy'),
        ),
    ]
