# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0035_auto_20170326_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='R',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Rentab. Hoy'),
        ),
    ]
