# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0036_auto_20170326_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='summary',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Dep\xf3sito'),
        ),
        migrations.AddField(
            model_name='summary',
            name='withdraw',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Reembolso'),
        ),
    ]
