# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0037_auto_20170416_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='B',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='withdraw',
        ),
        migrations.AddField(
            model_name='summary',
            name='returnGeom',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='Rentab. Geom(%)'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='R',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True, verbose_name='R'),
        ),
    ]
