# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0038_auto_20170417_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='R',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='returnGeom',
        ),
        migrations.AddField(
            model_name='summary',
            name='profitabilityCurrent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rentab. Actual(%)'),
        ),
    ]
