# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0040_auto_20170430_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sector')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'Sector',
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='ShareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo Acci\xf3n')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ShareType',
                'verbose_name': 'Tipo Acci\xf3n',
                'verbose_name_plural': 'Tipos Acciones',
            },
        ),
        migrations.AddField(
            model_name='share',
            name='sector',
            field=models.ForeignKey(blank=True, db_column='idSector', null=True, on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='share',
            name='shareType',
            field=models.ForeignKey(blank=True, db_column='idShareType', null=True, on_delete=django.db.models.deletion.CASCADE, to='sharesWebApp.ShareType', verbose_name='Tipo'),
        ),
    ]
