# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0042_share_targetvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefonds',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count'),
        ),
    ]
