# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0043_sharefonds_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefonds',
            name='avgVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Vol. Medio'),
        ),
        migrations.AddField(
            model_name='sharefonds',
            name='maxVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Vol. M\xe1ximo'),
        ),
        migrations.AddField(
            model_name='sharefonds',
            name='minVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Vol. M\xednimo'),
        ),
    ]
