# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0044_auto_20170430_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharefonds',
            name='avgVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Vol. Medio'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='maxVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Vol. M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='minVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Vol. M\xednimo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% del fondo'),
        ),
    ]
