# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0047_auto_20190620_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercomissions',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='depositwithdraw',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='right',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='share',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Notas'),
        ),
    ]
