# Generated by Django 2.2.3 on 2019-11-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesWebApp', '0048_auto_20190620_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharetype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo Accion', 'verbose_name_plural': 'Tipos Acciones'},
        ),
        migrations.AlterField(
            model_name='alarm',
            name='maxPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Limite Superior'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='minPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Limite Inferior'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='share',
            field=models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Share'),
        ),
        migrations.AlterField(
            model_name='brokercomissions',
            name='broker',
            field=models.ForeignKey(db_column='idBroker', default=1, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Broker', verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='currency',
            field=models.ForeignKey(db_column='idCurrency', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Currency', verbose_name='Divisa'),
        ),
        migrations.AlterField(
            model_name='depositwithdraw',
            name='broker',
            field=models.ForeignKey(db_column='idBroker', default=1, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Broker', verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='transaction',
            field=models.ForeignKey(db_column='idTransaction', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Transaction', verbose_name='Transaccion'),
        ),
        migrations.AlterField(
            model_name='right',
            name='transaction',
            field=models.ForeignKey(db_column='idTransaction', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Transaction', verbose_name='Transaccion'),
        ),
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.ForeignKey(db_column='idCurrency', default=1, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Currency', verbose_name='Divisa'),
        ),
        migrations.AlterField(
            model_name='share',
            name='index',
            field=models.ForeignKey(blank=True, db_column='idIndex', null=True, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Index', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='share',
            name='sector',
            field=models.ForeignKey(blank=True, db_column='idSector', null=True, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='share',
            name='shareType',
            field=models.ForeignKey(blank=True, db_column='idShareType', null=True, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.ShareType', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='fond',
            field=models.ForeignKey(db_column='idFond', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Fond', verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='maxPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Maximo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='maxVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Vol. Maximo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='minPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Precio Minimo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='minVolume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Vol. Minimo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='period',
            field=models.ForeignKey(db_column='idPeriod', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Period', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='sharefonds',
            name='share',
            field=models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Share', verbose_name='Accion'),
        ),
        migrations.AlterField(
            model_name='sharehistory',
            name='share',
            field=models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Share', verbose_name='Accion'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.ForeignKey(db_column='idBroker', default=1, on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Broker', verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='share',
            field=models.ForeignKey(db_column='idShare', on_delete=django.db.models.deletion.PROTECT, to='sharesWebApp.Share', verbose_name='Accion'),
        ),
    ]
